services:
  - type: web
    name: jobconnect
    runtime: python
    rootDir: JobConnect
    buildCommand: "./build.sh"
    startCommand: "gunicorn JobConnect.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: jobconnect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_SECRET_KEY
        sync: false
      - key: SUPABASE_BUCKET_NAME
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false

databases:
  - name: jobconnect-db
    databaseName: jobconnect
    user: jobconnect