# Generated by Django 5.2.7 on 2025-10-14 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='applicant_avatars/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/permits/', verbose_name='Business Permit'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_documents/logos/', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='setup_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
