# Generated by Django 5.2.7 on 2025-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicantprofile_image_employerprofile_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('corp', 'Corporation'), ('llc', 'LLC'), ('solo', 'Sole Proprietorship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='team_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51+', '51+ Employees')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='year_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/permits/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_documents/logos/'),
        ),
    ]
