# Generated by Django 5.2.7 on 2025-10-17 07:38

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicantprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='Contact number must be at least 10 digits.')]),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='degree',
            field=models.CharField(blank=True, help_text='e.g., BS in Information Technology', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow employers to view your profile.'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Cebu City, Philippines', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='profile_completeness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX only. Max 5MB.', null=True, upload_to=accounts.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='skills_summary',
            field=models.TextField(blank=True, help_text='Comma-separated list of your key skills.'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='year_level',
            field=models.CharField(blank=True, help_text='e.g., 3rd Year, Graduate', max_length=50),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('retail', 'Retail'), ('manu', 'Manufacturing'), ('edu', 'Education'), ('nonprofit', 'Non-Profit'), ('construction', 'Construction'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
