# Generated by Django 5.2.7 on 2025-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_applicantprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='setup_step_progress',
            field=models.IntegerField(default=1),
        ),
    ]
