# Generated by Django 5.2.7 on 2025-10-17 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_applicantprofile_setup_step_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='image',
            field=models.ImageField(blank=True, default='https://abewsixrnjnfrlhotyvu.supabase.co/storage/v1/object/sign/jobconnect-media/defaults/default-avatar.png', null=True, upload_to='profile_images/applicant/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX only. Max 5MB.', null=True, upload_to='applicant_documents/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
