# Generated by Django 5.2.7 on 2025-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_applicantprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default-avatar.png', null=True, upload_to='profile_images/applicant/'),
        ),
    ]
