# Generated by Django 5.2.7 on 2025-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_applicantprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
